#
# 必要に応じて、データベースの接続情報を変更してください。
#
[DATABASE]
driver = postgres    # DBドライバ名
user = fsepuser      # DBユーザー
password = admin1234 # DBパスワード
host = 163.43.70.68  # DB host IP or Host Name
name = sugarcrm      # DB名
port = 15432

# JDBCドライバー定義
[JDBC]
driver_class = org.postgresql.Driver