/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/mfa/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mfa Verify */
        post: operations["mfa_verify_api_v1_auth_mfa_verify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/mfa/resend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mfa Resend */
        post: operations["mfa_resend_api_v1_auth_mfa_resend_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout All */
        post: operations["logout_all_api_v1_auth_logout_all_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Session */
        get: operations["get_session_api_v1_auth_session_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/password-setup/request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Password Setup Request */
        post: operations["password_setup_request_api_v1_auth_password_setup_request_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/password-setup/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Password Setup Verify */
        post: operations["password_setup_verify_api_v1_auth_password_setup_verify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/password-setup/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Password Setup Complete */
        post: operations["password_setup_complete_api_v1_auth_password_setup_complete_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/companies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Companies
         * @description 会社一覧（SC-91・system_admin 専用）＋複数ソート/項目別フィルタ/CSV/固定行 契約（§1.8.1①②③④）。
         */
        get: operations["list_companies_api_v1_admin_companies_get"];
        put?: never;
        /**
         * Create Company
         * @description 会社作成（SC-91・`status=suspended` で作成・code/db_identifier 一意）。
         */
        post: operations["create_company_api_v1_admin_companies_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/companies/{company_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Company
         * @description 会社詳細（SC-92）。
         */
        get: operations["get_company_api_v1_admin_companies__company_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Company
         * @description 会社プロフィール更新（SC-92・name/color/icon）。
         */
        patch: operations["update_company_api_v1_admin_companies__company_id__patch"];
        trace?: never;
    };
    "/api/v1/admin/companies/{company_id}/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Company Settings
         * @description 会社設定フラグ更新（SC-92・記名時は非開示を無効化して整合）。
         */
        patch: operations["update_company_settings_api_v1_admin_companies__company_id__settings_patch"];
        trace?: never;
    };
    "/api/v1/admin/companies/{company_id}/quest-groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Company Quest Groups
         * @description 会社のクエストグループ候補一覧（SC-92・B.3・system_admin 専用・所属割当の候補）。
         */
        get: operations["list_company_quest_groups_api_v1_admin_companies__company_id__quest_groups_get"];
        put?: never;
        /**
         * Create Company Quest Group
         * @description クエストグループを作成（SC-92・B.3・system_admin 専用）。変更系＝Origin/CSRF 必須（P3）。
         */
        post: operations["create_company_quest_group_api_v1_admin_companies__company_id__quest_groups_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/companies/{company_id}/quest-groups/{group_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Company Quest Group
         * @description クエストグループを削除（SC-92・B.3.1・空グループのみ・トゥームストーン）。変更系＝Origin/CSRF 必須（P3）。
         */
        delete: operations["delete_company_quest_group_api_v1_admin_companies__company_id__quest_groups__group_id__delete"];
        options?: never;
        head?: never;
        /**
         * Rename Company Quest Group
         * @description クエストグループをリネーム（SC-92・B.3.1・system_admin・`name` のみ）。変更系＝Origin/CSRF 必須（P3）。
         */
        patch: operations["rename_company_quest_group_api_v1_admin_companies__company_id__quest_groups__group_id__patch"];
        trace?: never;
    };
    "/api/v1/admin/companies/{company_id}/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Company Accounts
         * @description 会社のアカウント一覧（SC-92・B.2・system_admin 専用）＋複数ソート/enum 多値フィルタ/CSV/固定行（§1.8.1①②③④）。
         */
        get: operations["list_company_accounts_api_v1_admin_companies__company_id__accounts_get"];
        put?: never;
        /**
         * Issue Company Account
         * @description アカウントを発行（SC-92・B.2・system_admin 専用）。変更系＝Origin/CSRF 必須（B.0.1 P3）。
         */
        post: operations["issue_company_account_api_v1_admin_companies__company_id__accounts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/companies/{company_id}/accounts/{account_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Edit Company Account
         * @description アカウント編集（SC-92・B.2・差分・system_admin 専用）。変更系＝Origin/CSRF 必須（B.0.1 P3）。
         */
        patch: operations["edit_company_account_api_v1_admin_companies__company_id__accounts__account_id__patch"];
        trace?: never;
    };
    "/api/v1/admin/companies/{company_id}/accounts/{account_id}/disable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Disable Account
         * @description アカウント無効化（B.2・全セッション破棄＋信頼端末失効・`last_system_admin` 拒否）。
         */
        post: operations["disable_account_api_v1_admin_companies__company_id__accounts__account_id__disable_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/companies/{company_id}/accounts/{account_id}/enable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Enable Account
         * @description アカウント再有効化（B.2）。
         */
        post: operations["enable_account_api_v1_admin_companies__company_id__accounts__account_id__enable_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/companies/{company_id}/accounts/{account_id}/password-reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Password Reset
         * @description 初回/再設定PWリンクを再送（B.2・A.7・旧リンク失効・非同期送信）。
         */
        post: operations["password_reset_api_v1_admin_companies__company_id__accounts__account_id__password_reset_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Own Accounts
         * @description 自社アカウント一覧（SC-93・B.2.1）＝B.2 と同形の契約（複数ソート/enum 多値フィルタ/CSV/固定行・§1.8.1①②③④）。
         */
        get: operations["list_own_accounts_api_v1_admin_accounts_get"];
        put?: never;
        /**
         * Issue Own Account
         * @description 自社アカウント発行（B.2.1・`system_role=general` 固定＝ロール付与は不可）。
         */
        post: operations["issue_own_account_api_v1_admin_accounts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/accounts/{account_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Edit Own Account
         * @description 自社アカウント編集（B.2.1・`system_role` 変更不可＝DTO が受け取らない）。
         */
        patch: operations["edit_own_account_api_v1_admin_accounts__account_id__patch"];
        trace?: never;
    };
    "/api/v1/admin/accounts/{account_id}/disable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Disable Own Account
         * @description 自社アカウント無効化（B.2.1・**system_admin は無効化不可**＝403）。
         */
        post: operations["disable_own_account_api_v1_admin_accounts__account_id__disable_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/accounts/{account_id}/enable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Enable Own Account
         * @description 自社アカウント再有効化（B.2.1）。
         */
        post: operations["enable_own_account_api_v1_admin_accounts__account_id__enable_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/accounts/{account_id}/password-reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Password Reset Own Account
         * @description 自社アカウントのPWリンク再送（B.2.1・A.7）。
         */
        post: operations["password_reset_own_account_api_v1_admin_accounts__account_id__password_reset_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/company-quest-groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Own Company Quest Groups
         * @description 自社のクエストグループ一覧（B.2.1・所属エディタの候補・セッション会社固定）。読み取りのみ。
         */
        get: operations["list_own_company_quest_groups_api_v1_admin_company_quest_groups_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/quest-groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Admin Quest Groups
         * @description 自分が `admin` のグループ一覧（SC-90・member_count 付き・admin 所属ゼロは 403）。
         */
        get: operations["list_admin_quest_groups_api_v1_admin_quest_groups_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/quest-groups/{group_id}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Quest Group Members
         * @description グループの参加メンバー一覧（当該グループの admin のみ・非 admin/不明は 404 存在秘匿）。
         */
        get: operations["list_quest_group_members_api_v1_admin_quest_groups__group_id__members_get"];
        put?: never;
        /**
         * Add Quest Group Member
         * @description 既存アカウントを自グループに参加追加（`role=member` 固定・SoD）。変更系＝Origin/CSRF 必須（P3）。
         */
        post: operations["add_quest_group_member_api_v1_admin_quest_groups__group_id__members_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/company-directory": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Company Directory
         * @description 自社アカウント・ディレクトリ（最小射影・QG管理者のみ＝admin 所属ゼロは 403）。
         */
        get: operations["company_directory_api_v1_admin_company_directory_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/quest-groups/{group_id}/members/{account_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Remove Quest Group Member
         * @description 自グループから除外（per-group トゥームストーン・204・冪等・アカウント本体は不変・SoD）。
         */
        delete: operations["remove_quest_group_member_api_v1_admin_quest_groups__group_id__members__account_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Me
         * @description 自分のプロフィール＋残高（正準・K.1）。identity＝accounts／残高＝会社DB users。画像署名URL は K.4 で。
         */
        get: operations["get_me_api_v1_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Me
         * @description 表示名・ロケールを編集（K.2）。accounts 更新＋会社DB users ミラー enqueue。変更系＝Origin/CSRF 必須。
         */
        patch: operations["update_me_api_v1_me_patch"];
        trace?: never;
    };
    "/api/v1/me/activities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get My Activities
         * @description 自分の活動履歴（G.6・新しい順・カーソル §1.8）。`kind`/`period` で絞り込み。読取専用。
         */
        get: operations["get_my_activities_api_v1_me_activities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Change Password
         * @description 自己パスワード変更（K.3）。現在PW 再認証→ポリシー検証→更新→全セッション破棄（要再ログイン）。変更系＝Origin/CSRF 必須。
         */
        post: operations["change_password_api_v1_me_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/avatar-image": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Put Avatar Image
         * @description プロフィールアバター画像を設定（K.4・multipart）。会社DB users 直接更新＋短TTL 署名URL 返却。変更系＝Origin/CSRF 必須。
         */
        put: operations["put_avatar_image_api_v1_me_avatar_image_put"];
        post?: never;
        /**
         * Delete Avatar Image
         * @description アバター画像を削除（既定に戻す・K.4）。変更系＝Origin/CSRF 必須。
         */
        delete: operations["delete_avatar_image_api_v1_me_avatar_image_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/background-image": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Put Background Image
         * @description コンテンツ背景画像を設定（K.4・全認証画面に反映・multipart）。変更系＝Origin/CSRF 必須。
         */
        put: operations["put_background_image_api_v1_me_background_image_put"];
        post?: never;
        /**
         * Delete Background Image
         * @description 背景画像をリセット（既定背景へ・K.4）。変更系＝Origin/CSRF 必須。
         */
        delete: operations["delete_background_image_api_v1_me_background_image_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request Email Change
         * @description 自己メール変更を**要求**（K.3・ダブルオプトイン ADR-0008）。現在PW 再認証→pending 化→新メールへ確認リンク。
         *
         *     202（確定待ち＝この時点では未反映）。変更系＝Origin/CSRF 必須。確定は `POST /me/email/confirm`。
         */
        post: operations["request_email_change_api_v1_me_email_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/email/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Confirm Email Change
         * @description メール変更の**確定**（K.3・ADR-0008）。**未認証＝トークンが認可**（新メール受信＝到達確認）。
         *
         *     `password-setup/complete` と同型＝セッション不要・CSRF 免除（トークンが唯一の資格）・Origin のみ検証。
         *     無効/期限切れ/使用済みトークンは 410。
         */
        post: operations["confirm_email_change_api_v1_me_email_confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Healthz
         * @description DB（管理DB）と Redis への疎通を確認する。
         */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AcceptedResponse
         * @description 常に同一（列挙耐性・A.7）。実際に送ったかは示さない。
         */
        AcceptedResponse: {
            /**
             * Status
             * @default accepted
             */
            status: string;
        };
        /**
         * AccountCreateRequest
         * @description アカウント発行の入力（B.2・SC-92）。想定外プロパティは拒否（Mass Assignment 防止・§B.6）。
         *
         *     `system_role` は enum 限定（`quest_group_admin` は不受理）。`memberships`＝初期所属（会社DB
         *     `quest_group_members`）を発行 Tx で outbox payload へ相乗（B.5 step3）。`role=admin` 可（B.2）。
         */
        AccountCreateRequest: {
            /** Display Name */
            display_name: string;
            /** Login Id */
            login_id: string;
            /** Email */
            email: string;
            /**
             * System Role
             * @default general
             * @enum {string}
             */
            system_role: "general" | "company_account_admin" | "system_admin";
            /**
             * Locale
             * @default ja
             * @enum {string}
             */
            locale: "ja" | "en";
            /** Memberships */
            memberships?: components["schemas"]["MembershipInput"][];
        };
        /**
         * AccountCreateSelfRequest
         * @description 会社アカウント管理者の発行入力（B.2.1）。**`system_role` は受け取らない**＝作れるのは
         *     `general` のみ（ロール付与は system_admin に集約・§8-⑯）。想定外プロパティは拒否（§B.6）。
         *     ただし `memberships` の `role=admin`（QG管理者任命）は自社スコープで可（B.2.1・2026-08-02 改定）。
         */
        AccountCreateSelfRequest: {
            /** Display Name */
            display_name: string;
            /** Login Id */
            login_id: string;
            /** Email */
            email: string;
            /**
             * Locale
             * @default ja
             * @enum {string}
             */
            locale: "ja" | "en";
            /** Memberships */
            memberships?: components["schemas"]["MembershipInput"][];
        };
        /**
         * AccountListItem
         * @description アカウント一覧の 1 行（SC-92・B.2）。`password_hash` 等の機密は含めない（§B.6）。
         *
         *     所属グループ/グループ内ロール（会社DB `quest_group_members`）は後続スライスで付与する。
         */
        AccountListItem: {
            /** Account Id */
            account_id: string;
            /** Display Name */
            display_name: string;
            /** Login Id */
            login_id: string;
            /** Email */
            email: string;
            /** System Role */
            system_role: string;
            /** Status */
            status: string;
            /** Last Login At */
            last_login_at?: string | null;
        };
        /** AccountListResponse */
        AccountListResponse: {
            /** Data */
            data: components["schemas"]["AccountListItem"][];
            /**
             * Pinned
             * @default []
             */
            pinned: components["schemas"]["AccountListItem"][];
            page_info: components["schemas"]["PageInfo"];
        };
        /**
         * AccountResponse
         * @description 発行/編集/状態変更結果のアカウント（機密は含めない・§B.6）。
         */
        AccountResponse: {
            /** Account Id */
            account_id: string;
            /** Display Name */
            display_name: string;
            /** Login Id */
            login_id: string;
            /** Email */
            email: string;
            /** System Role */
            system_role: string;
            /** Status */
            status: string;
            /** Password Set */
            password_set: boolean;
        };
        /**
         * AccountUpdateRequest
         * @description アカウント編集の入力（差分・B.2）。未指定フィールドは変更しない（`model_dump(exclude_unset=True)`）。
         *
         *     想定外プロパティは拒否（Mass Assignment 防止・§B.6）。`memberships` を指定すると希望有効所属の
         *     全集合として差分適用（会社DB `quest_group_members` を直接 upsert/トゥームストーン・B.3）。未指定は所属に触れない。
         */
        AccountUpdateRequest: {
            /** Display Name */
            display_name?: string | null;
            /** Login Id */
            login_id?: string | null;
            /** Email */
            email?: string | null;
            /** System Role */
            system_role?: ("general" | "company_account_admin" | "system_admin") | null;
            /** Memberships */
            memberships?: components["schemas"]["MembershipInput"][] | null;
        };
        /**
         * AccountUpdateSelfRequest
         * @description 会社アカウント管理者の編集入力（B.2.1・差分）。**`system_role` は変更不可**（受け取らない）。
         *     `memberships` は自社スコープで差分適用可（`role=admin` の任命/剥奪も可・B.2.1・2026-08-02）。
         */
        AccountUpdateSelfRequest: {
            /** Display Name */
            display_name?: string | null;
            /** Login Id */
            login_id?: string | null;
            /** Email */
            email?: string | null;
            /** Memberships */
            memberships?: components["schemas"]["MembershipInput"][] | null;
        };
        /**
         * AvatarImageResponse
         * @description `PUT /me/avatar-image` の応答（K.4）＝設定後の短TTL 署名URL。
         */
        AvatarImageResponse: {
            /** Avatar Image Url */
            avatar_image_url: string;
        };
        /**
         * BackgroundImageResponse
         * @description `PUT /me/background-image` の応答（K.4）＝設定後の短TTL 署名URL。
         */
        BackgroundImageResponse: {
            /** Background Image Url */
            background_image_url: string;
        };
        /** Body_put_avatar_image_api_v1_me_avatar_image_put */
        Body_put_avatar_image_api_v1_me_avatar_image_put: {
            /** File */
            file: string;
        };
        /** Body_put_background_image_api_v1_me_background_image_put */
        Body_put_background_image_api_v1_me_background_image_put: {
            /** File */
            file: string;
        };
        /**
         * CompanyCreateRequest
         * @description 会社作成の入力（SC-91）。`company_code` は大文字正規化＋形式検証（§4.1）。想定外プロパティ拒否。
         */
        CompanyCreateRequest: {
            /** Name */
            name: string;
            /** Company Code */
            company_code: string;
            /** Db Identifier */
            db_identifier: string;
            /** Color */
            color?: string | null;
            /** Icon Image Path */
            icon_image_path?: string | null;
        };
        /**
         * CompanyDetail
         * @description 会社詳細＋設定フラグ＋件数（SC-92）。
         */
        CompanyDetail: {
            /** Company Id */
            company_id: string;
            /** Company Code */
            company_code: string;
            /** Name */
            name: string;
            /** Db Identifier */
            db_identifier: string;
            /** Status */
            status: string;
            /** Color */
            color: string;
            /** Icon Image Path */
            icon_image_path?: string | null;
            /** Mfa Required */
            mfa_required: boolean;
            /** Vote Anonymized */
            vote_anonymized: boolean;
            /** Hide Voters From Managers */
            hide_voters_from_managers: boolean;
            /** Account Count */
            account_count: number;
        };
        /**
         * CompanyListItem
         * @description 会社一覧の 1 行（SC-91）。group_count（会社DB `quest_groups`）はドメインC実装時に付与。
         */
        CompanyListItem: {
            /** Company Id */
            company_id: string;
            /** Company Code */
            company_code: string;
            /** Name */
            name: string;
            /** Db Identifier */
            db_identifier: string;
            /** Status */
            status: string;
            /** Color */
            color: string;
            /** Icon Image Path */
            icon_image_path?: string | null;
            /** Account Count */
            account_count: number;
        };
        /** CompanyListResponse */
        CompanyListResponse: {
            /** Data */
            data: components["schemas"]["CompanyListItem"][];
            /**
             * Pinned
             * @default []
             */
            pinned: components["schemas"]["CompanyListItem"][];
            page_info: components["schemas"]["PageInfo"];
        };
        /**
         * CompanyProfileUpdateRequest
         * @description 会社プロフィール更新（SC-92・差分）。company_code/db_identifier は不変（受け取らない）。
         */
        CompanyProfileUpdateRequest: {
            /** Name */
            name?: string | null;
            /** Color */
            color?: string | null;
            /** Icon Image Path */
            icon_image_path?: string | null;
        };
        /**
         * CompanySettingsUpdateRequest
         * @description 会社設定フラグ更新（SC-92・差分）。
         */
        CompanySettingsUpdateRequest: {
            /** Vote Anonymized */
            vote_anonymized?: boolean | null;
            /** Hide Voters From Managers */
            hide_voters_from_managers?: boolean | null;
            /** Mfa Required */
            mfa_required?: boolean | null;
        };
        /**
         * CursorPageInfo
         * @description カーソルページングのページ情報（§1.8）。
         */
        CursorPageInfo: {
            /** Next Cursor */
            next_cursor?: string | null;
            /** Has Next */
            has_next: boolean;
        };
        /**
         * DirectoryItem
         * @description 自社ディレクトリの 1 行（B.4・**最小射影**＝PII/role/組織構造は出さない）。
         */
        DirectoryItem: {
            /** Account Id */
            account_id: string;
            /** Display Name */
            display_name: string;
            /** Avatar Url */
            avatar_url?: string | null;
        };
        /** DirectoryResponse */
        DirectoryResponse: {
            /** Data */
            data: components["schemas"]["DirectoryItem"][];
            page_info: components["schemas"]["PageInfo"];
        };
        /**
         * EmailChangeAcceptedResponse
         * @description メール変更要求の受理応答（202・確定待ち・ADR-0008）。この時点では未反映。
         */
        EmailChangeAcceptedResponse: {
            /**
             * Status
             * @default accepted
             */
            status: string;
        };
        /**
         * EmailChangeConfirmRequest
         * @description メール変更の**確定**（K.3・未認証＝トークンが認可・ADR-0008 §2.3）。想定外プロパティ拒否（§2.2）。
         */
        EmailChangeConfirmRequest: {
            /** Token */
            token: string;
        };
        /**
         * EmailChangeConfirmedResponse
         * @description メール変更確定の応答（200・ADR-0008）。未認証 EP のため identity 全体は返さない。
         */
        EmailChangeConfirmedResponse: {
            /**
             * Status
             * @default confirmed
             */
            status: string;
        };
        /**
         * EmailChangeRequest
         * @description 自己メール変更の**要求**（K.3・現在PW 再認証・ダブルオプトイン ADR-0008）。想定外プロパティ拒否（§2.2）。
         */
        EmailChangeRequest: {
            /** New Email */
            new_email: string;
            /** Current Password */
            current_password: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LoginRequest */
        LoginRequest: {
            /** Company Code */
            company_code: string;
            /** Login Id */
            login_id: string;
            /** Password */
            password: string;
        };
        /** LoginResponse */
        LoginResponse: {
            /** Status */
            status: string;
            session?: components["schemas"]["Session"] | null;
            mfa?: components["schemas"]["MfaChallenge"] | null;
        };
        /**
         * MeAccountDTO
         * @description identity（accounts 源泉・K.1）＝ログインID/メール/ロケール。
         */
        MeAccountDTO: {
            /** Login Id */
            login_id: string;
            /** Email */
            email: string;
            /** Locale */
            locale: string;
        };
        /**
         * MeActivitiesResponse
         * @description `GET /me/activities`（履歴・G.6）＝カーソル一覧共通形（§1.8）。新しい順。
         */
        MeActivitiesResponse: {
            /** Data */
            data: components["schemas"]["MeActivityDTO"][];
            page_info: components["schemas"]["CursorPageInfo"];
        };
        /**
         * MeActivityDTO
         * @description 活動履歴の1行（G の `activities` 元帳・G.6）。残高そのものではなく付与/消費の記録。
         *
         *     `amount` は常に正・方向は `kind`（*_gain/*_spend）。`ref_type`/`ref_id` は多態参照（NULL 可・対でセット）。
         */
        MeActivityDTO: {
            /** Id */
            id: string;
            /** Kind */
            kind: string;
            /** Amount */
            amount: number;
            /** Reason */
            reason: string;
            /** Quest Id */
            quest_id?: string | null;
            /** Ref Type */
            ref_type?: string | null;
            /** Ref Id */
            ref_id?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * MeBalanceDTO
         * @description 残高（会社DB `users`・読み取り専用・canonical は G の activities・K.0）。
         *
         *     `level`/`xp_to_next`/`level_span` は G の純粋レベル関数（データモデル §7）で `xp` から算出。
         */
        MeBalanceDTO: {
            /** Level */
            level: number;
            /** Xp */
            xp: number;
            /** Xp To Next */
            xp_to_next: number;
            /** Level Span */
            level_span: number;
            /** Coin Balance */
            coin_balance: number;
            /** Skill Point Balance */
            skill_point_balance: number;
        };
        /**
         * MeProfileDTO
         * @description プロフィール表示（K.1）。display_name は accounts 源泉。画像は署名URL（K.4・未設定は None）。
         */
        MeProfileDTO: {
            /** Display Name */
            display_name: string;
            /** Avatar Image Url */
            avatar_image_url?: string | null;
            /** Background Image Url */
            background_image_url?: string | null;
        };
        /**
         * MeResponse
         * @description `GET /me`（正準・K.1）＝identity＋プロフィール＋残高。ダッシュボード hero も同読取（I.1 と両立）。
         */
        MeResponse: {
            account: components["schemas"]["MeAccountDTO"];
            profile: components["schemas"]["MeProfileDTO"];
            balance: components["schemas"]["MeBalanceDTO"];
            /** System Role */
            system_role: string;
        };
        /**
         * MeUpdateRequest
         * @description プロフィール編集の入力（K.2・allowlist）。**`display_name`/`locale` のみ**受理。
         *
         *     残高・`system_role`・`status`・`password_set`・`login_id`・`email` は編集不可＝想定外プロパティは
         *     拒否（extra=forbid＝Mass Assignment 防止・§2.2）。email/PW は K.3 の専用 EP（再認証）。
         */
        MeUpdateRequest: {
            /** Display Name */
            display_name?: string | null;
            /** Locale */
            locale?: ("ja" | "en") | null;
        };
        /**
         * MemberAddRequest
         * @description 参加追加の入力（B.4）。既存アカウントをディレクトリで選択。想定外プロパティ拒否（§B.6）。
         *
         *     **`role` は受け取らない**＝QG管理者の参加追加は `role=member` 固定（`admin` 任命は不可・§8-⑯）。
         */
        MemberAddRequest: {
            /**
             * Account Id
             * Format: uuid
             */
            account_id: string;
        };
        /**
         * MemberListItem
         * @description グループの参加メンバー 1 行（`quest_group_members`×`users`）。機密は含めない（§B.6）。
         */
        MemberListItem: {
            /** Account Id */
            account_id: string;
            /** Display Name */
            display_name: string;
            /** Role */
            role: string;
        };
        /** MemberListResponse */
        MemberListResponse: {
            /** Data */
            data: components["schemas"]["MemberListItem"][];
        };
        /**
         * MembershipInput
         * @description 初期所属/所属差分の 1 要素（会社DB `quest_group_members`・B.2/B.3/B.5）。
         *
         *     `role=admin`＝QG管理者任命（system_admin＋会社アカウント管理者が可・B.2.1）。想定外プロパティ拒否。
         */
        MembershipInput: {
            /**
             * Group Id
             * Format: uuid
             */
            group_id: string;
            /**
             * Role
             * @default member
             * @enum {string}
             */
            role: "member" | "admin";
        };
        /**
         * MembershipResponse
         * @description 参加追加の結果（会社DB `quest_group_members` の 1 行）。
         */
        MembershipResponse: {
            /** Account Id */
            account_id: string;
            /** Group Id */
            group_id: string;
            /** Role */
            role: string;
        };
        /**
         * MfaChallenge
         * @description login `mfa_required` 応答の mfa（A.1・ADR-0004 §2.4）。実在は本人に既知（PW照合後）。
         */
        MfaChallenge: {
            /**
             * Delivery
             * @default email
             */
            delivery: string;
            /** Masked To */
            masked_to: string;
            /** Expires In */
            expires_in: number;
            /** Resend Available In */
            resend_available_in: number;
        };
        /** MfaResendResponse */
        MfaResendResponse: {
            /** Expires In */
            expires_in: number;
            /** Resend Available In */
            resend_available_in: number;
        };
        /** MfaVerifyReq */
        MfaVerifyReq: {
            /** Code */
            code: string;
            /**
             * Trust Device
             * @default false
             */
            trust_device: boolean;
        };
        /** OkResponse */
        OkResponse: {
            /**
             * Status
             * @default ok
             */
            status: string;
        };
        /**
         * PageInfo
         * @description オフセットページングの page_info（README §1.8）。
         */
        PageInfo: {
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Per Page */
            per_page: number;
        };
        /**
         * PasswordChangeRequest
         * @description 自己パスワード変更の入力（K.3・現在PW 再認証）。想定外プロパティ拒否（§2.2）。
         */
        PasswordChangeRequest: {
            /** Current Password */
            current_password: string;
            /** New Password */
            new_password: string;
        };
        /**
         * PasswordResetResponse
         * @description PWリンク再送の結果（A.7）。
         */
        PasswordResetResponse: {
            /** Status */
            status: string;
        };
        /** PasswordSetupCompleteReq */
        PasswordSetupCompleteReq: {
            /** Token */
            token: string;
            /** New Password */
            new_password: string;
        };
        /** PasswordSetupRequestReq */
        PasswordSetupRequestReq: {
            /** Company Code */
            company_code: string;
            /** Login Id */
            login_id: string;
        };
        /** PasswordSetupVerifyReq */
        PasswordSetupVerifyReq: {
            /** Token */
            token: string;
        };
        /** PasswordSetupVerifyResponse */
        PasswordSetupVerifyResponse: {
            /** Valid */
            valid: boolean;
            /** Login Id */
            login_id: string;
        };
        /**
         * QuestGroupCreateRequest
         * @description クエストグループ作成の入力（B.3・system_admin）。`quest_group_code` は大文字正規化＋形式検証（§5.4）。
         *
         *     想定外プロパティは拒否（Mass Assignment 防止・§B.6）。会社内一意は application で担保（重複=409）。
         */
        QuestGroupCreateRequest: {
            /** Quest Group Code */
            quest_group_code: string;
            /** Name */
            name: string;
        };
        /**
         * QuestGroupListItem
         * @description 自分が `admin` のグループ 1 行（SC-90 グループ切替）。
         */
        QuestGroupListItem: {
            /** Group Id */
            group_id: string;
            /** Quest Group Code */
            quest_group_code: string;
            /** Name */
            name: string;
            /** Member Count */
            member_count: number;
        };
        /** QuestGroupListResponse */
        QuestGroupListResponse: {
            /** Data */
            data: components["schemas"]["QuestGroupListItem"][];
        };
        /**
         * QuestGroupRenameRequest
         * @description クエストグループのリネーム入力（B.3.1・`name` のみ）。`quest_group_code` は不変（受け取らない）。
         */
        QuestGroupRenameRequest: {
            /** Name */
            name: string;
        };
        /**
         * Session
         * @description A.6 セッションスキーマ（GET /auth/session の応答・login authenticated 応答に内包）。
         */
        Session: {
            /** Account Id */
            account_id: string;
            /** Company Id */
            company_id: string;
            /** Company Code */
            company_code: string;
            /** System Role */
            system_role: string;
            /** Locale */
            locale: string;
            user: components["schemas"]["SessionUser"];
            /**
             * Is Qg Admin
             * @default false
             */
            is_qg_admin: boolean;
        };
        /** SessionUser */
        SessionUser: {
            /** User Id */
            user_id: string | null;
            /** Display Name */
            display_name: string;
            /** Avatar Url */
            avatar_url?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mfa_verify_api_v1_auth_mfa_verify_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MfaVerifyReq"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mfa_resend_api_v1_auth_mfa_resend_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MfaResendResponse"];
                };
            };
        };
    };
    logout_all_api_v1_auth_logout_all_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_session_api_v1_auth_session_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
        };
    };
    password_setup_request_api_v1_auth_password_setup_request_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordSetupRequestReq"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AcceptedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    password_setup_verify_api_v1_auth_password_setup_verify_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordSetupVerifyReq"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PasswordSetupVerifyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    password_setup_complete_api_v1_auth_password_setup_complete_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordSetupCompleteReq"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_companies_api_v1_admin_companies_get: {
        parameters: {
            query?: {
                q?: string | null;
                status?: string | null;
                sort?: string | null;
                account_count_min?: number | null;
                account_count_max?: number | null;
                format?: string | null;
                columns?: string | null;
                pin_ids?: string | null;
                page?: number;
                per_page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanyListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_company_api_v1_admin_companies_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompanyCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanyDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_company_api_v1_admin_companies__company_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanyDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_company_api_v1_admin_companies__company_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompanyProfileUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanyDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_company_settings_api_v1_admin_companies__company_id__settings_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompanySettingsUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanyDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_company_quest_groups_api_v1_admin_companies__company_id__quest_groups_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuestGroupListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_company_quest_group_api_v1_admin_companies__company_id__quest_groups_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuestGroupCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuestGroupListItem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_company_quest_group_api_v1_admin_companies__company_id__quest_groups__group_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company_id: string;
                group_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rename_company_quest_group_api_v1_admin_companies__company_id__quest_groups__group_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company_id: string;
                group_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuestGroupRenameRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuestGroupListItem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_company_accounts_api_v1_admin_companies__company_id__accounts_get: {
        parameters: {
            query?: {
                q?: string | null;
                status?: string | null;
                system_role?: string | null;
                sort?: string | null;
                pin_ids?: string | null;
                format?: string | null;
                columns?: string | null;
                page?: number;
                per_page?: number;
            };
            header?: never;
            path: {
                company_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    issue_company_account_api_v1_admin_companies__company_id__accounts_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AccountCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    edit_company_account_api_v1_admin_companies__company_id__accounts__account_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company_id: string;
                account_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AccountUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    disable_account_api_v1_admin_companies__company_id__accounts__account_id__disable_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company_id: string;
                account_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    enable_account_api_v1_admin_companies__company_id__accounts__account_id__enable_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company_id: string;
                account_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    password_reset_api_v1_admin_companies__company_id__accounts__account_id__password_reset_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company_id: string;
                account_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PasswordResetResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_own_accounts_api_v1_admin_accounts_get: {
        parameters: {
            query?: {
                q?: string | null;
                status?: string | null;
                system_role?: string | null;
                sort?: string | null;
                pin_ids?: string | null;
                format?: string | null;
                columns?: string | null;
                page?: number;
                per_page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    issue_own_account_api_v1_admin_accounts_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AccountCreateSelfRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    edit_own_account_api_v1_admin_accounts__account_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AccountUpdateSelfRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    disable_own_account_api_v1_admin_accounts__account_id__disable_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    enable_own_account_api_v1_admin_accounts__account_id__enable_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    password_reset_own_account_api_v1_admin_accounts__account_id__password_reset_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PasswordResetResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_own_company_quest_groups_api_v1_admin_company_quest_groups_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuestGroupListResponse"];
                };
            };
        };
    };
    list_admin_quest_groups_api_v1_admin_quest_groups_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuestGroupListResponse"];
                };
            };
        };
    };
    list_quest_group_members_api_v1_admin_quest_groups__group_id__members_get: {
        parameters: {
            query?: {
                q?: string | null;
            };
            header?: never;
            path: {
                group_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_quest_group_member_api_v1_admin_quest_groups__group_id__members_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                group_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemberAddRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MembershipResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    company_directory_api_v1_admin_company_directory_get: {
        parameters: {
            query?: {
                q?: string | null;
                page?: number;
                per_page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DirectoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_quest_group_member_api_v1_admin_quest_groups__group_id__members__account_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                group_id: string;
                account_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_me_api_v1_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
        };
    };
    update_me_api_v1_me_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MeUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_my_activities_api_v1_me_activities_get: {
        parameters: {
            query?: {
                kind?: ("xp_gain" | "coin_gain" | "coin_spend" | "sp_gain" | "sp_spend") | null;
                period?: "this_week" | "last_week" | "this_month" | "all";
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeActivitiesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    change_password_api_v1_me_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordChangeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_avatar_image_api_v1_me_avatar_image_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_put_avatar_image_api_v1_me_avatar_image_put"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AvatarImageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_avatar_image_api_v1_me_avatar_image_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    put_background_image_api_v1_me_background_image_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_put_background_image_api_v1_me_background_image_put"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BackgroundImageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_background_image_api_v1_me_background_image_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    request_email_change_api_v1_me_email_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmailChangeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmailChangeAcceptedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirm_email_change_api_v1_me_email_confirm_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmailChangeConfirmRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmailChangeConfirmedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
